{{- if and .Values.otelCollector.enabled (not .Values.iax.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iax-otel-demo.name" . }}-iax-credentials
  labels:
    {{- include "iax-otel-demo.labels" (dict "Chart" .Chart "Release" .Release "name" "iax-credentials") | nindent 4 }}
type: Opaque
stringData:
  IAX_OTLP_ENDPOINT: {{ .Values.iax.otlpEndpoint | quote }}
  IAX_OTLP_INSECURE: {{ .Values.iax.otlpInsecure | quote }}
  IAX_OTLP_INSECURE_SKIP_VERIFY: {{ .Values.iax.otlpInsecureSkipVerify | quote }}
  IAX_INGESTION_USERNAME: {{ .Values.iax.ingestionUsername | quote }}
  IAX_INGESTION_PASSWORD: {{ .Values.iax.ingestionPassword | quote }}
{{- end }}
